#!/usr/bin/env bash

# Automatically installs the virtdev system using archinstall
# then sets up any remaining configuration.
#
# This script will:
#
#   1. Assume two disks exist
#       a. /dev/vda = system
#       b. /dev/vdb = home
#   2. Compute actual virtual disk sizes
#   3. Patch sentinel values in config.json
#   4. Run archinstall
#   5. Run post-install steps
#       1. Fix XBOOTLDR partition type
#       2. Configure automounting of home partition by label
#       3. Delete bootloader entries generated by archinstall
#       4. Generate new bootloader entries in XBOOTLDR partition
#       5. Reconfigure bootloader
#       6. Enable services
#          1. systemd-networkd
#          2. systemd-resolved
#          2. sshd
#       7. Lock all accounts to disable password-based login
#       8. Configure sudo for the dev user
#
# config.json stores 0 B as a sentinel for dynamic partition lengths.
# Bypassing this script and running archinstall directly
# should fail during partition creation. This is intentional.
#
# The installed system is left mounted at /mnt by archinstall.
# Post-install steps run via arch-chroot against /mnt.
#

set -euo pipefail

config=/root/archinstall/config.json
creds=/root/archinstall/creds.json

# Patch sentinel partition lengths with real disk geometry

disk_size() {
  lsblk --bytes --nodeps --noheadings --output SIZE "${1}" | tr -d ' '
}

sector_size() {
  lsblk --bytes --nodeps --noheadings --output PHY-SEC "${1}" | tr -d ' '
}

vda_bytes="$(disk_size /dev/vda)"
vdb_bytes="$(disk_size /dev/vdb)"

vda_sector_size="$(sector_size /dev/vda)"
vdb_sector_size="$(sector_size /dev/vdb)"

mib=$(( 1024 * 1024 ))

# /dev/vda layout:
#
#    0 MiB -    1 MiB    alignment gap
#    1 MiB -  513 MiB    ESP               512 MiB fat32 vda1
#  513 MiB - 1537 MiB    XBOOTLDR         1024 MiB fat32 vda2
# 1537 MiB -  END        root              100   %  ext4 vda3
#
esp_start=$((1 * mib))
esp_length=$((512 * mib))

# XBOOTLDR partition size is fixed at 1024 MiB

root_start=$((1537 * mib))
root_length=$((vda_bytes - root_start - mib))


# /dev/vdb layout:
#
#   0 MiB -   1 MiB    alignment gap
#   1 MiB - END        home             100 % ext4 vdb1
#
home_start=$((1 * mib))
home_length=$((vdb_bytes - home_start - mib))

if ((root_length <= 0 || home_length <= 0)); then
  >&2 printf 'virtdev: disk too small: root_length=%d home_length=%d\n' \
             "${root_length}" "${home_length}"
  exit 1
fi

tmp=$(mktemp)
jq                                                          \
    --argjson esp_start       "${esp_start}"                \
    --argjson esp_length      "${esp_length}"               \
    --argjson root_start      "${root_start}"               \
    --argjson root_length     "${root_length}"              \
    --argjson home_start      "${home_start}"               \
    --argjson home_length     "${home_length}"              \
    --argjson vda_sector_size "${vda_sector_size}"          \
    --argjson vdb_sector_size "${vdb_sector_size}"          \
    '
    (.disk_config.device_modifications[0].partitions[].start.sector_size,
     .disk_config.device_modifications[0].partitions[].size.sector_size) |= {"value": $vda_sector_size, "unit": "B"} |
    (.disk_config.device_modifications[1].partitions[].start.sector_size,
     .disk_config.device_modifications[1].partitions[].size.sector_size) |= {"value": $vdb_sector_size, "unit": "B"} |
    .disk_config.device_modifications[0].partitions[0].start |= (.value = $esp_start   | .unit = "B") |
    .disk_config.device_modifications[0].partitions[0].size  |= (.value = $esp_length  | .unit = "B") |
    .disk_config.device_modifications[0].partitions[2].start |= (.value = $root_start  | .unit = "B") |
    .disk_config.device_modifications[0].partitions[2].size  |= (.value = $root_length | .unit = "B") |
    .disk_config.device_modifications[1].partitions[0].start |= (.value = $home_start  | .unit = "B") |
    .disk_config.device_modifications[1].partitions[0].size  |= (.value = $home_length | .unit = "B")
    ' "${config}" > "${tmp}" && mv "${tmp}" "${config}"

printf 'virtdev: disk layout patched\n'
printf 'virtdev: vda(esp=%d xbootldr=%d root=%d sector_size=%d)\n' \
       "${esp_length}" "$((1024 * mib))" "${root_length}" "${vda_sector_size}"
printf 'virtdev: vdb(home=%d sector_size=%d)\n' \
       "${home_length}" "${vdb_sector_size}"

# Run archinstall

archinstall                 \
    --config "${config}"    \
    --creds  "${creds}"     \
    --silent

# Post-install steps

# Set vda2 GPT partition type to XBOOTLDR = EA00
# since it's required for systemd-boot to discover it
# and archinstall creates it as a plain fat32 partition
sgdisk --typecode=2:ea00 /dev/vda
printf 'virtdev: set vda2 partition type XBOOTLDR = EA00\n'

# Mount home partition by label rather than UUID
# in order enable project machines to swap in home disks
e2label /dev/vdb1 home
home_uuid="$(blkid -s UUID -o value /dev/vdb1)"
sed -i "s|^UUID=${home_uuid}|LABEL=home|" /mnt/etc/fstab
printf 'virtdev: home partition labelled and configured\n'

# The loader entries generated by archinstall assume kernel is ESP
rm -f /mnt/efi/loader/entries/*.conf
printf 'virtdev: generated bootloader entries erased\n'

root_uuid="$(blkid -s UUID -o value /dev/vda3)"
mkdir -p /mnt/boot/loader/entries
cat > /mnt/boot/loader/entries/arch.conf <<ENTRY
title   Arch Linux
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=UUID=${root_uuid} rw rootfstype=ext4 console=tty0 console=ttyS0
ENTRY
printf 'virtdev: bootloader entry written\n'

cat > /mnt/efi/loader/loader.conf <<CONF
default arch.conf
timeout 0
editor  no
CONF
printf 'virtdev: boot loader configuration written\n'

arch-chroot /mnt systemctl enable systemd-networkd systemd-resolved sshd
printf 'virtdev: services enabled\n'

# Lock password-based login on all accounts
arch-chroot /mnt passwd -l root
arch-chroot /mnt passwd -l dev
printf 'virtdev: accounts locked\n'

# Set up sudo for the dev user
printf 'dev ALL=(ALL:ALL) NOPASSWD: ALL\n' > /mnt/etc/sudoers.d/dev
chmod 440 /mnt/etc/sudoers.d/dev
printf 'virtdev: sudo configured for dev user\n'
