#!/usr/bin/env bash

set -euo pipefail

while (( $# > 0 )); do
  if [[ "${1}" == dev@127.0.0.1 || "${1}" == 127.0.0.1 ]]; then
    shift
    break
  fi
  shift
done
(( $# > 0 )) || exit 98
exec bash -c "$*"
